# NumPy (array-oriented)

由于 NumPy 提供了易于使用的 C API，因此可以很容易地将数据传递给以低级语言编写的外部库，也可以使外部库将数据作为 NumPy 数组返回给 Python

对于 large arrays of data，NumPy 很强大，原因是：
1. NumPy 在内部将数据存储在连续的内存块中，而与其他内置 Python 对象无关。NumPy 用 C 语言编写的算法库可以在此内存上运行，而无需任何类型检查或其他开销。NumPy 数组使用的内存也比内置 Python 序列少得多。
2. NumPy 操作无需使用 Python `for` 循环即可在整个数组上执行复杂的计算。

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2 # multiply sequence by 2

Wall time: 31 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.34 s


### The NumPy ndarray: A Multidimensional Array Object

NumPy 的主要功能之一是其N维数组对象（即 *ndarray* ）

In [1]:
import numpy as np

In [2]:
# Generate some raw data
data = np.random.randn(2, 3)

In [3]:
data

array([[ 0.52423136, -0.50749845,  0.25848575],
       [-1.67021263, -1.0317727 , -1.21460268]])

In [4]:
data * 10

array([[  5.24231365,  -5.07498449,   2.58485747],
       [-16.70212628, -10.31772698, -12.14602679]])

In [5]:
data + data

array([[ 1.04846273, -1.0149969 ,  0.51697149],
       [-3.34042526, -2.0635454 , -2.42920536]])

所有在数组里的元素必须是相同类型，每个数组都有一个 *shape* (一个表示每个维的大小的元组) 以及 *dtype* (一个描述数组数据类型的对象)

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### Creating ndarrays

`array` 方程用于创建数组，它接受 sequence-like object

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列 nested sequences（如等长的列表）将转换为多维数组

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

通过 `ndim` 来确认数组的维度， 再次巩固 `shape` 的用法

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

除非特定表明，不然`array`会自动为其创造的数组推断出最符合特征的数据类型

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

也有其他 function 可以创建数组，例如`zeros()`,`ones()`以及`empty()`

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.empty((2, 3, 2))

array([[[1.16285369e-311, 1.90979621e-311],
        [1.90130823e-311, 2.13048377e-311],
        [2.22385159e-311, 2.03711596e-311]],

       [[2.58883487e-311, 2.59732285e-311],
        [2.63127478e-311, 2.62278680e-311],
        [2.65673873e-311, 2.66522671e-311]]])

并不能完全假设 `np.empty()`会返回零值，他有时候会返回一些无用值（详情请看 [stackoverflow](https://stackoverflow.com/questions/51028426/initializing-numpy-array-from-np-empty) )

以下是一些常用的创建数组的 function

Function | Description
:- | :-
`array` | 不用解释了吧~
`asarray` | 将输入转换为 *ndarray*，但如果输入已经是 *ndarray*，则不复制
`arange` | 就像 `range()` 一样，只不过形成的是数组
`ones`, `ones_like` | 不用解释了吧， `one_like` 是相当于复制一个存在的数组只不过换成1
`zeros`, `zeros_like` | 就像上面一样，只不过是0
`empty`, `empty_like` | 不用解释了把
`full`, `full_like` | 像上面一样，只不过将所有值设置为指示的“填充值”，`full_like` 同理
`eye`, `identity` | 创建一个N×N单位矩阵（对角线上为1，其他地方为0）

### Data Type for ndarrays

在创建数组的时候，可以通过`dtype`来设置数据类型

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [4]:
arr1.dtype

dtype('float64')

以下是可选择的数据类型

Type | Type Code | Description
:- | :- | :-
int8, uint8 | i1, u1 | 有/无符号的 8-bit integer
int16, uint16 | i2, u2 | ~16-bit
int32, uint32 | i4, u4 | ~32-bit
int64, uint64 | i8, u8 | ~64-bit
float16 | f2 | 半精度 floating point
float32 | f4 or f | 标准单精度 floating point；与 C float 兼容
float64 | f8 or d | 标准双精度 floating point；与 C Double 和 Python 的 built-in float 兼容
float128 | f16 or g | 扩展精度 floating point
complex64, complex128, complex256 | c8, c16, c32 | 复数分别由两个32、64或128个浮点数表示
bool | ? | True or False
object | O | Python对象类型； 一个值可以是任何Python对象
string_ | S | 定长ASCII字符串类型（每个字符1个字节）； 例如，要创建长度为10的字符串 *dtype*，请使用`S10`
unicode_ | U | 固定长度的Unicode类型（特定于平台的字节数）；与 `string_` 用法相同，例如`U10`

`astype` 可以帮助转换或强行转换一个数组的数据类型

In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int32')

In [7]:
float_arr = arr.astype(np.float64)

In [8]:
float_arr.dtype

dtype('float64')

**警告！** 如果将 floating point 转换成 integer，那么小数点将会被删减

In [9]:
arr = np.array([3.7, -1.2, 2.4, 5.8, 16.29])

In [10]:
arr

array([ 3.7 , -1.2 ,  2.4 ,  5.8 , 16.29])

In [11]:
arr.astype(np.int32)

array([ 3, -1,  2,  5, 16])

如果一个数组用 string 来表达数字了，可以通过 `astype` 来转换成数字形式

In [12]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [13]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

使用`numpy.string_`类型时请务必小心，因为 NumPy 中的 string data 是固定大小的，可能会不出 warning 地删减你的 input

string 无法转换成 float64，这个时候就会出现 *ValueError*

另一种 `dtype` 的用法如下：

In [2]:
int_array = np.arange(10)

In [3]:
calibers = np.array([.22, .270, .357, .380, .44, .5], dtype = np.float64)

In [4]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

调用 `astype` 总是会创建一个新数组（数据的副本），即使新 `dtype` 与旧 `dtype` 相同

### Arithmetic with NumPy Arrays

Arrays 对数据的批处理操作而无需编写任何for循环被称作 *vectorization* 大小相等的数组之间的任何算术运算都按元素应用运算

In [6]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [7]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [10]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

大小不同的 array 之间的操作称作 *broadcasting*

### Basic Indexing and Slicing

与 Python 内置列表的第一个重要区别是数组切片是原始数组上的 *views*
这意味着不会复制数据，并且对 *views* 的任何修改将反映在源数组中

In [11]:
arr = np.arange(10)

In [12]:
arr[5:8] = 12

In [14]:
arr_slice = arr[5:8]

In [15]:
arr_slice[1] = 12345

In [16]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

`:` 会对数组里所有元素赋值

In [17]:
arr_slice[:] = 64

In [18]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

如果要复制 ndarray 的一部分而不是整体，则需要单独复制该数组，例如 `arr[5:8].copy()`

对于2维的数组操作，会有所不同

In [19]:
arr2d = np.array([[1, 2, 3], [4 ,5 ,6], [7, 8, 9]])

In [20]:
arr2d[2]

array([7, 8, 9])

In [21]:
arr2d[0][2]

3

In [22]:
arr2d[0, 2]

3

In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [7, 8, 9], [10, 11, 12]])

In [24]:
arr3d

array([list([[1, 2, 3], [4, 5, 6]]), list([7, 8, 9]), list([10, 11, 12])],
      dtype=object)

In [25]:
arr3d[0]

[[1, 2, 3], [4, 5, 6]]

In [26]:
old_values = arr3d[0].copy()

In [27]:
arr3d[0] = 42

In [28]:
arr3d

array([42, list([7, 8, 9]), list([10, 11, 12])], dtype=object)

In [29]:
arr3d[0] = old_values

In [30]:
arr3d

array([list([[1, 2, 3], [4, 5, 6]]), list([7, 8, 9]), list([10, 11, 12])],
      dtype=object)

#### Indexing with slices

In [32]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

因此，slice 将沿着轴选择一系列元素。 将表达式`arr2d [：2]`读为“选择 arr2d 的前两行”可能会有所帮助

In [34]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [35]:
arr2d[1, :2]

array([4, 5])

In [36]:
arr2d[:2, 2]

array([3, 6])

In [37]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

所以 `array[(1), (2)]`中（1）代表行，（2）代表列

### Boolean Indexing

In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [39]:
data = np.random.randn(7, 4)

In [40]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [41]:
data

array([[-0.03831075,  0.6498441 ,  0.32394369,  0.79694962],
       [ 0.06959597,  1.63515311, -0.77837886, -0.82006134],
       [-1.86562631,  0.65574719,  0.44401191, -1.23178659],
       [-0.46449838,  1.07051415, -0.78798995, -1.42413429],
       [ 0.818449  , -0.50705554, -0.41411142, -0.52550891],
       [ 1.26482944,  0.47326858,  0.03313031, -1.22448352],
       [-1.07748498, -0.15839601,  0.52607033,  1.35647898]])

In [42]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [43]:
data[names == 'Bob']

array([[-0.03831075,  0.6498441 ,  0.32394369,  0.79694962],
       [-0.46449838,  1.07051415, -0.78798995, -1.42413429]])

Boolean 的长度必须与其索引的数组轴的长度相同。如果 Boolean 的长度不正确, Boolean selection 将不会失败，因此，在使用此功能时，请小心

In [44]:
data[names == 'Bob', 2:]

array([[ 0.32394369,  0.79694962],
       [-0.78798995, -1.42413429]])

In [45]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [46]:
data[~(names == 'Bob')]

array([[ 0.06959597,  1.63515311, -0.77837886, -0.82006134],
       [-1.86562631,  0.65574719,  0.44401191, -1.23178659],
       [ 0.818449  , -0.50705554, -0.41411142, -0.52550891],
       [ 1.26482944,  0.47326858,  0.03313031, -1.22448352],
       [-1.07748498, -0.15839601,  0.52607033,  1.35647898]])

In [47]:
mask = (names == 'Bob') | (names == 'Will')

In [48]:
mask

array([ True, False,  True,  True,  True, False, False])

In [49]:
data[mask]

array([[-0.03831075,  0.6498441 ,  0.32394369,  0.79694962],
       [-1.86562631,  0.65574719,  0.44401191, -1.23178659],
       [-0.46449838,  1.07051415, -0.78798995, -1.42413429],
       [ 0.818449  , -0.50705554, -0.41411142, -0.52550891]])

在 Boolean 数组里面，要用 `&` 和 `|` 代替 `and` 和 `or`

In [50]:
data[data < 0] = 0

In [51]:
data

array([[0.        , 0.6498441 , 0.32394369, 0.79694962],
       [0.06959597, 1.63515311, 0.        , 0.        ],
       [0.        , 0.65574719, 0.44401191, 0.        ],
       [0.        , 1.07051415, 0.        , 0.        ],
       [0.818449  , 0.        , 0.        , 0.        ],
       [1.26482944, 0.47326858, 0.03313031, 0.        ],
       [0.        , 0.        , 0.52607033, 1.35647898]])

In [52]:
data[names != 'Joe'] = 7

In [53]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.06959597, 1.63515311, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.26482944, 0.47326858, 0.03313031, 0.        ],
       [0.        , 0.        , 0.52607033, 1.35647898]])

### Fancy Indexing

In [54]:
arr = np.empty((8, 4))

In [55]:
for i in range(8):
    arr[i] = i

In [56]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [57]:
arr[[4 ,3 ,0 ,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [58]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [59]:
arr = np.arange(32).reshape((8, 4)) # reshape change the shape of an array

In [60]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [61]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

这相当于选择了(1, 0), (5, 3), (7, 1), (2, 2)

In [62]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

第一项仍然表示选择的行是顺序，第二项表示选择该行全部列的数据，但先后顺序按照后面`[0, 3, 1, 2]`

不同于 slicing，fancy indexing 将会复制数据到新的数组里面

### Transposing Arrays and Swapping Axes

In [64]:
arr = np.arange(15).reshape((3,5))

In [65]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

`array.T` 就是用来 transpose 一个数组的

In [67]:
arr = np.random.randn(6, 3)

In [68]:
arr

array([[-0.93076469, -0.27217193,  0.23004885],
       [-0.70245774, -1.00975035,  1.28407006],
       [ 0.35953693,  0.00806786,  0.26074916],
       [ 0.75419463,  0.60613568,  2.08535228],
       [ 0.04433652, -2.00198838,  0.1473529 ],
       [-0.38587448,  2.20939816, -0.80994618]])

In [69]:
np.dot(arr.T, arr)

array([[ 2.20871097,  0.48136839,  0.86945483],
       [ 0.48136839, 10.35053654, -2.17758529],
       [ 0.86945483, -2.17758529,  6.79616835]])

`np.dot` 用于矩阵乘法

In [70]:
arr = np.arange(16).reshape((2, 2, 4))

In [71]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [72]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

第一第二 axis 互换了然后第三 axis 保持不变

ndarray里有一个方程`swapaxes`，它使用一对 axis numbers 并切换指示的 axes 以重新排列数据：

In [73]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])