## Universal Functions: Fast Element - Wise Array Functions

*ufunc* 就是在 Numpy 里面通常看到的 function，例如`sqrt`和`exp`这一类（通常叫做 *unary ufuncs*；还有`add`和`maximum`这一类的（叫做 *binary ufuncs*）

1. *ufunc* 也可以返回多个数组，例如`modf`就很像 python 的 built-in `divmod` 一样

In [1]:
import numpy as np

In [2]:
arr = np.random.randn(7) * 5

In [3]:
arr

array([  1.23111986, -13.91116137,   5.26884548,   2.39409698,
        -4.43422299,  -2.4583342 ,   3.46041534])

In [4]:
remainder, whole_part = np.modf(arr)

In [5]:
remainder

array([ 0.23111986, -0.91116137,  0.26884548,  0.39409698, -0.43422299,
       -0.4583342 ,  0.46041534])

In [6]:
whole_part

array([  1., -13.,   5.,   2.,  -4.,  -2.,   3.])

2. *ufunc* 也接受 `out` 的参数来进行数组内操作（只不过会有提示 Warning not Error！）

In [7]:
np.sqrt(arr)

<ipython-input-7-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.10955841,        nan, 2.29539658, 1.54728697,        nan,
              nan, 1.86021916])

In [8]:
np.sqrt(arr, arr)

<ipython-input-8-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.10955841,        nan, 2.29539658, 1.54728697,        nan,
              nan, 1.86021916])

下面是一些比较常见的 *unary ufuncs*

Function | Description
:- | :-
`abs`, `fabs` | 不用解释了吧~
`sqrt` | ~？
`square` | ~！
`exp` | ~(⊙o⊙)？
`log`, `log10`, `log2`, `log1p` | (　o=^•ェ•)o　┏━┓
`sign` | 计算每个元素的符号：1（正），0（零）或–1（负）
`ceil` | 计算每个元素的上限（例如大于或等于该数字的最小整数）
`floor` | 计算每个元素的下限（即小于或等于每个元素的最大整数）
`rint` | 将元素四舍五入到最接近的整数，并保留 dtype
`modf` | 将数组的分数和整数部分作为单独的数组返回
`isnan` | 返回 Boolean 数组，指示每个值是否为NaN（非数字）
`isfinite`, `isinf` | 返回 Boolean 数组，分别指示每个元素是有限的（non-inf，non-NaN）还是无限的
`cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Σ(っ °Д °;)っ
`arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | (:◎)≡
`logical_not` | 计算非x元素的真值（等效于〜arr）

`logical_not` 这个可能有些模糊如果第一次接触，下面给个例子：

In [9]:
x = np.arange(5)

In [10]:
x

array([0, 1, 2, 3, 4])

In [11]:
np.logical_not(x < 3)

array([False, False, False,  True,  True])

接下来是比较常见的 *binary universal functions*:

Function | Description
:- | :-
`add` | 加
`subtract` | 减
`multiply` | 乘
`divide`, `floor_divide`| 除（把余数去掉）
`power` | 幂
`maximum`, `fmax` | 最大
`minimum`, `fmin` | 最小
`mod` | 逐元素系数（除法余数）
`copysign` | 将第二个参数中的值的符号复制到第一个参数中的值
`greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not equal` | 赌大小了喂
`logical_and`, `logical_or`, `logical_xor` | 计算逻辑运算的逐元素真值（等效于中缀运算符）